# Install all bun dependencies and run tests, linting and typechecks

name: Bun Linting and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-client:
    name: "Test Client Code"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: cd client 
    - run: bun i
    - run: bun run --cwd client lint
    - run: bun run --cwd client test:ci

  lint-server:
    name: "Lint Server Code"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: cd server
    - run: bun i
    - run: bun run --cwd server lint
    - run: bun run --cwd server tsc
