# Install all bun dependencies and run tests, linting and typechecks

name: Bun Linting and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-client:
    name: "Test Client Code"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: cd pacakges/client && bun i && cd ../../
    - run: bun run client:lint
    # - run: bun run client:test-ci

  lint-server:
    name: "Test Server Code"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: cd pacakges/client && bun i && cd ../../
    - run: bun run server:lint
    - run: bun run server:tsc
    - run: bun run server:test
